[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "cloud-project-api"
version = "0.1.0"
description = "FastAPI backend"
requires-python = ">=3.9" 

# Only scanning app/ folder
[tool.setuptools.packages.find]
where = ["."]
include = ["app*"]
